export default {
  canvas: 'The Canvas',
  assistants: 'Assistants (Agents)',
  skills: 'Skills',
  workflows: 'Workflows',
  orchestration: 'Planner, Director & Advisor',
  discussions: 'Discussions',
  loops: 'Loops',
  'safety-rules': 'Safety Rules',
  schedules: 'Schedules',
  memory: 'Memory',
  resources: 'Resources',
  connections: 'Connections (MCP)',
  git: 'Git Integration',
  'external-folders': 'External Folders',
  monitoring: 'Monitoring & Audit',
  settings: 'Settings & Credentials',
  users: 'Users & Roles',
}
